name = "dab"

[empty]
w= 650
h = 500

[[features]]
key = "user"
kind = "user_image"
x = 150
y = 0
w = 500
h = 500
default_user = true

[[features]]
key = "dab"
kind = "image"
x = 0
y = 0
w = 500
h = 500
overlay_image_path = "./templates/dab/dab_image.png"