name = "boo"

[[features]]
key = "text1"
kind = "split_text"
x = 35
y = 54
w = 200
h = 60
font_size = 40
font_color = [0,0,0,255]

[[features]]
key = "text2"
kind = "split_text"
x = 267
y = 57
w = 150
h = 60
font_size = 40
font_color = [0,0,0,255]