name = "bed"

[[features]]
key = "user1"
kind = "user_image"
x = 25
y = 100
w = 100
h = 100
default_user = true

[[features]]
key = "user1"
kind = "user_image"
x = 25
y = 300
w = 100
h = 100

[[features]]
key = "user1"
kind = "user_image"
x = 53
y = 450
w = 70
h = 70

[[features]]
key = "user2"
kind = "user_image"
x = 53
y = 575
w = 70
h = 70