name = "brazzers"

[empty]
w = 500
h = 500

[[features]]
key = "user"
kind = "user_image"
default_user = true
x = 0
y = 0
w = 500
h = 500

[[features]]
key = "logo"
kind = "image"
x = 200
y = 375
w = 300
h = 150
overlay_image_path = "./templates/brazzers/brazzers.png"